module.exports = {
  product_title: "Produkty",
  product_cleanclip_url: "https://cleanclip.cc/sk",
  support_title: "Podpora",
  support_roadmap_name: "Cesta",
  support_roadmap_url: "/sk/docs/roadmap.html",
  download_roadmap_name: "Stiahnuť",
  download_roadmap_url: "/sk/download",
  license_manager_name: "Správca licencií",
  contact_support_name: "Kontaktovať podporu",
  feature_request_name: "Spätná väzba",

  sales_title: "Predaj",
  sales_affiliate_name: "Partneri",
  sales_affiliate_label: "Získajte až $10.00 za každú predanú položku",
  sales_discounts_name: "Špeciálne zľavy",
  sales_discounts_url: "/sk/discounts",
  sales_discounts_label: "Zľavy od 4-9",

  company_title: "Spoločnosť",
  company_articles_name: "Články",
  company_articles_url: "/sk/articles",
  company_developer_blog_name: "Vývojárske blogy",
  company_developer_blog_url: "/sk/developer",
  company_translation_name: "Pomoc s prekladom",
  label_new: "Nové",
  company_privacy_name: "Zásady ochrany osobných údajov",
  company_privacy_url: "/sk/docs/privacy",
}