module.exports = {
  product_title: "المنتج",
  product_cleanclip_url: "https://cleanclip.cc/ar",
  support_title: "الدعم",
  support_roadmap_name: "خريطة الطريق",
  support_roadmap_url: "/ar/docs/roadmap.html",
  download_roadmap_name: "تنزيل",
  download_roadmap_url: "/ar/download",
  license_manager_name: "مدير التراخيص",
  contact_support_name: "الاتصال بالدعم",
  feature_request_name: "طلب الميزات",

  sales_title: "المبيعات",
  sales_affiliate_name: "برنامج الشراكة",
  sales_affiliate_label: "اكسب حتى 10.00 $ في كل عملية بيع",
  sales_discounts_name: "عروض خاصة",
  sales_discounts_url: "/ar/discounts",
  sales_discounts_label: "خصومات تتراوح بين 4-9",

  company_title: "الشركة",
  company_articles_name: "المقالات",
  company_articles_url: "/ar/articles",
  company_developer_blog_name: "مدونة المطورين",
  company_developer_blog_url: "/ar/developer",
  company_translation_name: "مساعدة في الترجمة",
  label_new: "جديد",
  company_privacy_name: "سياسة الخصوصية",
  company_privacy_url: "/ar/docs/privacy",
}