module.exports = {
  product_title: "Produkt",
  product_cleanclip_url: "https://cleanclip.cc/se",
  support_title: "Support",
  support_roadmap_name: "Vägkarta",
  support_roadmap_url: "/se/docs/roadmap.html",
  download_roadmap_name: "Ladda ner",
  download_roadmap_url: "/se/download",
  license_manager_name: "Licenshanterare",
  contact_support_name: "Kontakta support",
  feature_request_name: "Återkoppling",

  sales_title: "Försäljning",
  sales_affiliate_name: "Partnerprogram",
  sales_affiliate_label: "Få upp till $10.00 per försäljning",
  sales_discounts_name: "Specialerbjudanden",
  sales_discounts_url: "/se/discounts",
  sales_discounts_label: "4-9% rabatt",

  company_title: "Företag",
  company_articles_name: "Artiklar",
  company_articles_url: "/se/articles",
  company_developer_blog_name: "Utvecklarblogg",
  company_developer_blog_url: "/se/developer",
  company_translation_name: "Hjälp med översättning",
  label_new: "Ny",
  company_privacy_name: "Integritetspolicy",
  company_privacy_url: "/se/docs/privacy",
}