module.exports = {
  collect_images_title: "Collecting Images",
  collect_images_subtitle: "With CleanClip, I can seamlessly find design inspiration without the need to constantly switch between apps. Just copy the images you like and paste them all at once when you return to the app.",
  collect_images_label: "Design",
  create_app_previews_title: "Creating App Preview Images",
  create_app_previews_subtitle: "Syncing data between iPhones and Macs can be a hassle at times. But now, with CleanClip, I can easily capture screenshots and copy all the information on your phone. CleanClip will automatically save all my copied records. Once you have collected all the information, I can effortlessly access it on my Mac and use it to create preview images.",
  create_app_previews_label: "Design",
  write_travel_plan_title: "Write travel plan",
  write_travel_plan_subtitle: "When I'm in the process of creating a travel plan, I often need to gather a multitude of images, screenshots, and text. CleanClip comes to my aid by allowing me to collect all this information in one go, making it convenient for me to use it later within the app.",
  write_travel_plan_label: "Write",
  search_email_templates_title: "Search email template",
  search_email_templates_subtitle: "As a marketer, I need to send different types of emails to various clients. CleanClip has been a great tool for me as it stores all the email templates I have used, enabling me to retrieve them whenever needed.",
  search_email_templates_label: "Marketing",
  submit_across_sites_title: "Submit project information on 40+ websites",
  submit_across_sites_subtitle: "When promoting an app, it is often required to submit project information to multiple websites. With CleanClip, I can save time and effort by copying the information once and using it multiple times without having to go back and forth between project documents and different websites. This convenience makes CleanClip truly remarkable.",
  submit_across_sites_label: "Solopreneur",
  search_command_history_title: "Search past commands",
  search_command_history_subtitle: "Some commonly used command parameters can be complex and hard to remember, like ffmpeg. However, I recall that I have used it before and I can easily find and use it in CleanClip.",
  search_command_history_label: "Terminal",
}