module.exports = {
  product_title: "产品",
  product_cleanclip_url: "https://cleanclip.cc/zh",
  support_title: "支持",
  support_roadmap_name: "路线图",
  support_roadmap_url: "/zh/docs/roadmap.html",
  download_roadmap_name: "下载",
  download_roadmap_url: "/zh/download",
  license_manager_name: "许可证管理器",
  contact_support_name: "联系支持",
  feature_request_name: "功能请求",

  sales_title: "销售",
  sales_affiliate_name: "联盟计划",
  sales_affiliate_label: "每单最多挣 $10.00",
  sales_discounts_name: "特别优惠",
  sales_discounts_url: "/zh/discounts",
  sales_discounts_label: "4-9 折优惠",

  company_title: "公司",
  company_articles_name: "文章",
  company_articles_url: "/zh/articles",
  company_developer_blog_name: "开发者博客",
  company_developer_blog_url: "/zh/developer",
  company_translation_name: "协助翻译",
  label_new: "新",
  company_privacy_name: "隐私政策",
  company_privacy_url: "/zh/docs/privacy",
}
