module.exports = {
  title: "特别优惠",
  subtitle: "为不同用户群体提供各种特权",
  student_title: "学生优惠",
  student_desc: '向正规学生提供<b>30%</b>的折扣，支持学习和探索。<a href="/jp/students">了解详情</a>',
  competitor_title: "竞争对手用户优惠",
  competitor_desc: '向我们竞争对手产品的用户提供<b>30%</b>的折扣，顺利支持产品切换。<a href="https://forms.gle/v1ya3x93Z1ud3H4A7" target="_blank">申请优惠</a>',
  open_source_contributor_title: "开源贡献者折扣",
  open_source_contributor_desc: '向为开源社区做出贡献的人们提供<b>10%</b>的折扣，以示感谢。<a href="https://forms.gle/m7TLTbSuZyJdfDgLA" target="_blank">申请优惠</a>',
  translator_title: "翻译贡献者奖励",
  translator_desc: '为帮助翻译产品的人们提供<b>$5 - $20</b>的折扣券，表示感谢，并在下次购买时表示感谢。<a class="" href="https://crowdin.com/project/cleanclipapp" target="_blank">参与翻译</a>',
  content_creator_title: "与内容创作者合作特权",
  content_creator_desc: '如果您是内容创作者，打算创建与 CleanClip 相关内容，在此提供宝贵的折扣代码，以提升内容的推广效果。合作邮件：<b>cooperation@cleanclip.cc</b>。',
  war_zone_title: "战争地区普通市民",
  war_zone_desc: '为居住在战争地区的普通市民提供55%的特别折扣，表达真诚的关怀和支持。<a href="https://forms.gle/sYErhfAD3KpFraqK8" target="_blank">注册居住地</a>',
}