module.exports = {
  title: "特別優待",
  subtitle: "為不同用戶群體提供各種特權",
  student_title: "學生優惠",
  student_desc: '向合法學生提供<b>30%</b>的折扣，支持學習和探索。<a href="/jp/students">了解詳情</a>',
  competitor_title: "競爭對手用戶優惠",
  competitor_desc: '向我們競爭對手產品的用戶提供<b>30%</b>的折扣，順利支持產品切換。<a href="https://forms.gle/v1ya3x93Z1ud3H4A7" target="_blank">申請優惠</a>',
  open_source_contributor_title: "開源貢獻者折扣",
  open_source_contributor_desc: '向為開源社區做出貢獻的人們提供<b>10%</b>的折扣，以示感謝。<a href="https://forms.gle/m7TLTbSuZyJdfDgLA" target="_blank">申請優惠</a>',
  translator_title: "翻譯貢獻者獎勵",
  translator_desc: '為幫助翻譯產品的人們提供<b>$5 - $20</b>的折扣券，表示感謝，並在下次購買時表示感謝。<a class="" href="https://crowdin.com/project/cleanclipapp" target="_blank">參與翻譯</a>',
  content_creator_title: "與內容創作者合作特權",
  content_creator_desc: '如果您是內容創作者，打算創建與 CleanClip 相關內容，在此提供寶貴的折扣代碼，以提升內容的推廣效果。合作郵件：<b>cooperation@cleanclip.cc</b>。',
  war_zone_title: "戰爭地區普通市民",
  war_zone_desc: '為居住在戰爭地區的普通市民提供55%的特別折扣，表達真誠的關懷和支持。<a href="https://forms.gle/sYErhfAD3KpFraqK8" target="_blank">註冊居住地</a>',
}