module.exports = {
  product_title: "Produkt",
  product_cleanclip_url: "https://cleanclip.cc/de",
  support_title: "Support",
  support_roadmap_name: "Roadmap",
  support_roadmap_url: "/de/docs/roadmap.html",
  download_roadmap_name: "Herunterladen",
  download_roadmap_url: "/de/download",
  license_manager_name: "Lizenzmanager",
  contact_support_name: "Support kontaktieren",
  feature_request_name: "Funktionsanfrage",

  sales_title: "Verkauf",
  sales_affiliate_name: "Partnerprogramm",
  sales_affiliate_label: "Verdiene bis zu $10.00 pro Bestellung",
  sales_discounts_name: "Sonderangebote",
  sales_discounts_url: "/de/discounts",
  sales_discounts_label: "4-9 Rabatt",

  company_title: "Unternehmen",
  company_articles_name: "Artikel",
  company_articles_url: "/de/articles",
  company_developer_blog_name: "Entwicklerblog",
  company_developer_blog_url: "/de/developer",
  company_translation_name: "Übersetzungshilfe",
  label_new: "Neu",
  company_privacy_name: "Datenschutzrichtlinie",
  company_privacy_url: "/de/docs/privacy",
}