module.exports = {
  title: "Special Offers",
  subtitle: "We offer a series of discounts for different user groups",
  student_title: "Student Discount",
  student_desc: 'We provide <b>30%</b> discount for full-time students to help them study and explore better. <a href="/gb/students">Learn More</a>',
  competitor_title: "Competitor User Discount",
  competitor_desc: 'If you are a user of our competitors, we offer <b>30%</b> discount to help you easily switch to our product. <a href="https://forms.gle/v1ya3x93Z1ud3H4A7" target="_blank">Apply for the discount</a>',
  open_source_contributor_title: "Open Source Contributor Discount",
  open_source_contributor_desc: 'For those who contribute to the open source community, we offer a <b>10%</b> discount to express our gratitude. <a href="https://forms.gle/m7TLTbSuZyJdfDgLA" target="_blank">Apply for the discount</a>',
  translator_title: "Translator Appreciation",
  translator_desc: 'For those who help us translate the product into other languages, we offer <b>$5 - $20</b> voucher to purchase our future products as a token of our gratitude. <a class="" href="https://crowdin.com/project/cleanclipapp" target="_blank">Start translating</a>',
  content_creator_title: "Content Creator Collaboration Discount",
  content_creator_desc: 'If you are a content creator planning to create content related to CleanClip, we are willing to provide an exclusive discount code to enhance the impact of your content promotion. Partnership email: <b>cooperation@cleanclip.cc</b>.',
  war_zone_title: "Ordinary People in War Zones",
  war_zone_desc: 'For ordinary civilians living in war zones, we offer a 55% special discount to express our care and support. <a href="https://forms.gle/sYErhfAD3KpFraqk8" target="_blank">Register your location</a>',
}