module.exports = {
  product_title: "Products",
  product_cleanclip_url: "https://cleanclip.cc/gb",
  support_title: "Support",
  support_roadmap_name: "Roadmap",
  support_roadmap_url: "/gb/docs/roadmap.html",
  download_roadmap_name: "Download",
  download_roadmap_url: "/gb/download",
  license_manager_name: "License Manager",
  contact_support_name: "Contact Support",
  feature_request_name: "Feature Request",

  sales_title: "Sales",
  sales_affiliate_name: "Affiliate Program",
  sales_affiliate_label: "Earn up to $10.00 per sale",
  sales_discounts_name: "Special Offers",
  sales_discounts_url: "/gb/discounts",
  sales_discounts_label: "4-9 discount",

  company_title: "Company",
  company_articles_name: "Articles",
  company_articles_url: "/gb/articles",
  company_developer_blog_name: "Developer Blog",
  company_developer_blog_url: "/gb/developer",
  company_translation_name: "Help with Translation",
  label_new: "New",
  company_privacy_name: "Privacy Policy",
  company_privacy_url: "/gb/docs/privacy",
}