module.exports = {
  title: "특별 혜택",
  subtitle: "다양한 사용자 그룹을 위해 다양한 혜택을 제공합니다",
  student_title: "학생 할인",
  student_desc: '전일제 학생을 위해 <b>30%</b> 할인을 제공하여 학습과 탐험을 더 잘 할 수 있도록 돕겠습니다. <a href="/ko/students">자세히 알아보기</a>',
  competitor_title: "경쟁사 사용자 할인",
  competitor_desc: '만약 당신이 우리의 경쟁사 사용자라면, <b>30%</b> 할인을 제공하여 우리 제품으로 쉽게 전환할 수 있도록 도와드리겠습니다. <a href="https://forms.gle/v1ya3x93Z1ud3H4A7" target="_blank">할인 신청하기</a>',
  open_source_contributor_title: "오픈 소스 기여자 할인",
  open_source_contributor_desc: '오픈 소스 커뮤니티에 기여하는 분들을 위해 <b>10%</b> 할인을 제공하여 감사의 마음을 전하겠습니다. <a href="https://forms.gle/m7TLTbSuZyJdfDgLA" target="_blank">할인 신청하기</a>',
  translator_title: "번역 기여자 보상",
  translator_desc: '제품을 다른 언어로 번역하는 데 도움을 주신 분들을 위해 <b>$5 - $20</b> 상품교환권을 제공하여 우리의 감사를 표현하겠습니다. <a class="" href="https://crowdin.com/project/cleanclipapp" target="_blank">번역하기</a>',
  content_creator_title: "콘텐츠 제작자 협업 할인",
  content_creator_desc: '콘텐츠 제작자이고 CleanClip 관련 콘텐츠를 만들 계획이라면, 콘텐츠 홍보 효과를 강화하기 위한 전용 할인 코드를 제공해 드립니다. 협업 이메일: <b>cooperation@cleanclip.cc</b>.',
  war_zone_title: "전쟁 지역의 일반 시민",
  war_zone_desc: '전쟁 지역에서 살고 있는 일반 시민을 위해 우리는 관심과 지원을 전하며 <b>55%</b> 특별 할인을 제공하겠습니다. <a href="https://forms.gle/sYErhfAD3KpFraqK8" target="_blank">거주 지역 등록하기</a>',
}