module.exports = {
  product_title: "제품",
  product_cleanclip_url: "https://cleanclip.cc/ko",
  support_title: "지원",
  support_roadmap_name: "로드맵",
  support_roadmap_url: "/ko/docs/roadmap.html",
  download_roadmap_name: "다운로드",
  download_roadmap_url: "/ko/download",
  license_manager_name: "라이센스 관리자",
  contact_support_name: "지원에 문의",
  feature_request_name: "피드백",
    
  sales_title: "판매",
  sales_affiliate_name: "제휴 프로그램",
  sales_affiliate_label: "주문 당 최대 $10.00를 벌 수 있습니다",
  sales_discounts_name: "특별 혜택",
  sales_discounts_url: "/ko/discounts",
  sales_discounts_label: "4-9 할인 혜택",
    
  company_title: "회사",
  company_articles_name: "기사",
  company_articles_url: "/ko/articles",
  company_developer_blog_name: "개발자 블로그",
  company_developer_blog_url: "/ko/developer",
  company_translation_name: "번역 지원",
  label_new: "새로운",
  company_privacy_name: "개인정보 정책",
  company_privacy_url: "/ko/docs/privacy",
}